# Generated by Django 3.2.8 on 2022-05-16 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='medicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreMedi', models.CharField(max_length=50, null=True, verbose_name='nomMedicamento')),
                ('precio', models.CharField(max_length=6, null=True, verbose_name='precioMedic')),
                ('descripcion', models.CharField(max_length=100, null=True, verbose_name='descMed')),
                ('FechaElabora', models.DateField()),
                ('FechaCaduc', models.DateField()),
                ('stock', models.IntegerField(null=True, verbose_name='descMed')),
                ('fabrica', models.CharField(max_length=50, null=True, verbose_name='nomMedicamento')),
                ('contenido', models.CharField(max_length=100, null=True, verbose_name='Content')),
                ('gramos', models.IntegerField(null=True, verbose_name='Gram')),
                ('caducado', models.IntegerField(null=True, verbose_name='Caduc')),
                ('motivoCaduc', models.CharField(max_length=100, verbose_name='MotCaduc')),
            ],
        ),
        migrations.CreateModel(
            name='paciente',
            fields=[
                ('rutPas', models.CharField(max_length=10, null=True, primary_key=True, serialize=False, verbose_name='RutPas')),
                ('Pnombre', models.CharField(max_length=20, null=True, verbose_name='PNombre ')),
                ('Snombre', models.CharField(max_length=20, null=True, verbose_name='SNombre ')),
                ('apellidoP', models.CharField(max_length=20, null=True, verbose_name='ApellidoP ')),
                ('apellidoM', models.CharField(max_length=20, null=True, verbose_name='ApellidoM ')),
            ],
        ),
        migrations.CreateModel(
            name='retiroMedicamento',
            fields=[
                ('Fecha', models.DateField()),
                ('rutPas', models.CharField(max_length=10, null=True, primary_key=True, serialize=False, verbose_name='RutPas')),
            ],
        ),
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=20, null=True, verbose_name='descrTipoUsu')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('RutUsuario', models.CharField(max_length=3, null=True, primary_key=True, serialize=False, verbose_name='IdUsuario')),
                ('PnombreUsuario', models.CharField(max_length=20, null=True, verbose_name='PNomUsu')),
                ('SnombreUsuario', models.CharField(max_length=20, null=True, verbose_name='SNomUsu')),
                ('APaternoUsuario', models.CharField(max_length=20, null=True, verbose_name='ApUsu')),
                ('AMaternoUsuario', models.CharField(max_length=20, null=True, verbose_name='ApMUsu')),
                ('correoUsuario', models.EmailField(max_length=30, null=True, verbose_name='CorreoUsuario')),
                ('contrasenaUsuario', models.CharField(max_length=16, null=True, verbose_name='ContrasenaUsuario')),
            ],
        ),
        migrations.CreateModel(
            name='tutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PnomTutor', models.CharField(max_length=20, null=True, verbose_name='PNomTutor ')),
                ('SnomTutor', models.CharField(max_length=20, null=True, verbose_name='SNomTutor ')),
                ('apellPTutor', models.CharField(max_length=20, null=True, verbose_name='PApellTutor ')),
                ('apellMTutor', models.CharField(max_length=20, null=True, verbose_name='SApellTutor ')),
                ('rutPaciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='reservar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosis', models.CharField(max_length=50, null=True, verbose_name='DosisMedic')),
                ('NumReservas', models.IntegerField(null=True, verbose_name='NumReserv')),
                ('Medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.usuario')),
                ('medicam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.medicamento')),
            ],
        ),
        migrations.CreateModel(
            name='preinscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalle', models.TextField(max_length=2000, null=True, verbose_name='Content')),
                ('Medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='CarnetPaciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comuna', models.CharField(max_length=20, null=True, verbose_name='PNombre ')),
                ('rutPaciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='CarnetInscFamil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector', models.CharField(max_length=40, null=True, verbose_name='sector')),
                ('rutPaciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.paciente')),
            ],
        ),
    ]
