# Generated by Django 3.2.8 on 2022-05-19 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='correoPaciente',
            field=models.EmailField(max_length=30, null=True, verbose_name='CorreoPaciente'),
        ),
    ]
